spring.datasource.url=jdbc:postgresql://localhost:5432/appliancemgmt
spring.datasource.username=postgres
spring.datasource.password=test123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=MySuperSecretKeyForJWTs
jwt.expiration=86400000

logging.level.com.zaxxer.hikari=DEBUG

#############################################
# EMAIL CONFIGURATION
#############################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587

frontend.url=http://localhost:4200


spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

resend.api.key=${RESEND_API_KEY}
resend.from=${RESEND_FROM}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Resend
