spring.datasource.url=jdbc:postgresql://localhost:5432/appliancemgmt
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=MySuperSecretKeyForJWTs