spring.datasource.url=jdbc:postgresql://localhost:5432/appliancemgmt
spring.datasource.username=postgres
spring.datasource.password=test123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=MySuperSecretKeyForJWTs
jwt.expiration=86400000
logging.level.com.zaxxer.hikari=DEBUG
#############################################
# EMAIL CONFIGURATION
#############################################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oussamaelater9@gmail.com
spring.mail.password=mvvj kwpy ilsc zkbv
frontend.url=http://localhost:4200
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
resend.api.key=
resend.from=elateroussama9@gmail.com