CREATE TABLE public.appliances (
                                   id bigint NOT NULL,
                                   created_at timestamp(6) without time zone NOT NULL,
                                   name character varying(255) NOT NULL,
                                   status character varying(255),
                                   test_end_date date,
                                   test_start_date date,
                                   client_id bigint NOT NULL,
                                   CONSTRAINT appliances_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'COMPLETED'::character varying])::text[])))
);



--
-- Name: appliances_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appliances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appliances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
                                id bigint NOT NULL,
                                address character varying(255),
                                company_name character varying(255) NOT NULL,
                                created_at timestamp(6) without time zone NOT NULL,
                                email character varying(255) NOT NULL,
                                industry character varying(255),
                                name character varying(255) NOT NULL,
                                phone character varying(255),
                                user_id bigint NOT NULL
);



--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluations (
                                    id bigint NOT NULL,
                                    created_at timestamp(6) without time zone NOT NULL,
                                    meeting_date timestamp(6) without time zone NOT NULL,
                                    notes character varying(255),
                                    outcome character varying(255) NOT NULL,
                                    appliance_id bigint NOT NULL,
                                    CONSTRAINT evaluations_outcome_check CHECK (((outcome)::text = ANY ((ARRAY['PASS'::character varying, 'FAIL'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying])::text[])))
);



--
-- Name: evaluations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.logs (
                             id bigint NOT NULL,
                             action character varying(255) NOT NULL,
                             created_at timestamp(6) without time zone,
                             details character varying(255),
                             entity character varying(255) NOT NULL,
                             "timestamp" timestamp(6) without time zone NOT NULL,
                             user_id bigint NOT NULL
);



--
-- Name: logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
                                     id bigint NOT NULL,
                                     client_id bigint,
                                     created_at timestamp(6) without time zone,
                                     message character varying(255),
                                     sender_id bigint
);



--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_read_by; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification_read_by (
                                             notification_id bigint NOT NULL,
                                             read_by bigint
);



--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) without time zone NOT NULL,
                                 notes character varying(255) NOT NULL,
                                 session_date timestamp(6) without time zone NOT NULL,
                                 status character varying(255) NOT NULL,
                                 appliance_id bigint,
                                 CONSTRAINT sessions_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'COMPLETED'::character varying])::text[])))
);



--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              address character varying(255),
                              created_at timestamp(6) without time zone,
                              email character varying(255),
                              name character varying(255),
                              password character varying(255) NOT NULL,
                              phone character varying(255),
                              role character varying(255) NOT NULL,
                              username character varying(255) NOT NULL,
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'CONSULTANT'::character varying, 'SUPERADMIN'::character varying])::text[])))
);



--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appliances appliances_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appliances
    ADD CONSTRAINT appliances_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: evaluations evaluations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluations
    ADD CONSTRAINT evaluations_pkey PRIMARY KEY (id);


--
-- Name: logs logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: clients uksrv16ica2c1csub334bxjjb59; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uksrv16ica2c1csub334bxjjb59 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: notification_read_by fk22as2o4qw6o4gbinccdmllfsy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification_read_by
    ADD CONSTRAINT fk22as2o4qw6o4gbinccdmllfsy FOREIGN KEY (notification_id) REFERENCES public.notification(id);


--
-- Name: evaluations fk2aq37q5q6l3pd6tpgn10atahb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluations
    ADD CONSTRAINT fk2aq37q5q6l3pd6tpgn10atahb FOREIGN KEY (appliance_id) REFERENCES public.appliances(id);


--
-- Name: sessions fk5xp514kt4efq47fjtcncp1e56; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fk5xp514kt4efq47fjtcncp1e56 FOREIGN KEY (appliance_id) REFERENCES public.appliances(id);


--
-- Name: logs fkgqy8beil5y4almtq1tiyofije; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT fkgqy8beil5y4almtq1tiyofije FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: appliances fkt78n33kdi883yk8ywa6a4x38i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appliances
    ADD CONSTRAINT fkt78n33kdi883yk8ywa6a4x38i FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: clients fktiuqdledq2lybrds2k3rfqrv4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fktiuqdledq2lybrds2k3rfqrv4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
