name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show environment
        run: |
          java -version
          mvn -version

      - name: Build and run tests
        run: mvn clean verify -e

      - name: Build Docker image
        run: docker build -t appliancemgmt .